### ISSUE TITLE
Add link to Seasonal Cups Order Form

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#1]
Assigning this to myself for now; will need to write copy for the Schools page for this and hyperlink to download
[Seasonal_Cups_Order_Form.pdf](https://github.com/vcfolger/southernicecreamtx.com/files/324046/Seasonal_Cups_Order_Form.pdf)
 the attached file.

**Comment by netintelpro** [comment]
Just sent you and Kelly admin creds to test site.

**Comment by vcfolger** [comment]
I wasn't sure how to add a PDF download, and my attempt is wonky. Can you make this better, so the name of the PDF is not the link itself, etc.? I'm referring to the "Seasonal Cups Order Form" bit towards the end of the page.
