### ISSUE TITLE
Homepage Banner animation

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#10]
Need to replace first banner with animation. Assigning to Kelly first. Kelly, assign this to John if/when you need him to do something to implement

**Comment by kelly-wolfe** [comment]
Will do!

**Comment by kelly-wolfe** [comment]
I still feel like this is low on the list of priorities. If y'all disagree, lemme know.

**Comment by kelly-wolfe** [comment]
I was trying to see if I could replace the home page animation myself the other night. I didn't think I published the change.

**Comment by kelly-wolfe** [comment]
Please replace the banner on homepage with #3 jkw_...

**Comment by kelly-wolfe** [comment]
Josh, I

**Comment by kelly-wolfe** [comment]
Whoops, I have been trying to figure out the not looping issue. I found other people have had more luck duplicating the animation and then looping them together. I can't seem to figure out how to do that either. I successfully duplicated it, but haven't worked out how to loop them. Is this something you may know how to do?

**Comment by kelly-wolfe** [comment]
Nevermind!! I found it!
