### ISSUE TITLE
Client wants phone number and address/get directions front and center on mobile

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#104]
Replace the animation (which they want to disable for mobile) with this? Kelly maybe mock up how this would look?

**Comment by kelly-wolfe** [comment]
I think this warrants a convo. Not following.

**Comment by vcfolger** [comment]
Thinking about this more...could you comp this up? Let's leave the animation as-is, just stick the phone number and "Get directions" link above it.

**Comment by kelly-wolfe** [comment]
I am not crazy about this change, but I guess this is how I want it to look.  Didn't want to do the teal button b/c it felt too heavy to me.  Should they agree to keep graphic and lose animation, could we use this still instead?  Just on mobile of course.  I noticed some other stuff which Chrisitna may have already addressed. I'd like the social media icons centered as well as menu icon on mobile.  

![homemobile](https://cloud.githubusercontent.com/assets/20116181/21688595/1642f590-d333-11e6-86f0-03616ab5c046.jpg)

**Comment by vcfolger** [comment]
Josh, see the change to add Phone and Get Directions to the Mobile version of the homepage. Let us know if her other requests (centering menu icon and social links) are a big deal to do.
