### ISSUE TITLE
Need more prominent "Book Now" on Ice Cream Parties page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#107]
For this page: http://66.147.244.191/~outhesi4/ice-cream-parties/

The call to action is especially far from the top on mobile. Especially to Bobby and Michelle.
We need to do a graphic on the page, maybe part of the header banner that could be clickable or right underneath, a prominent "Book My Event" button.
![img_6172](https://cloud.githubusercontent.com/assets/20050245/21618935/9fe96c64-d1aa-11e6-89e6-290e37c23d09.PNG)

**Comment by kelly-wolfe** [comment]
For consistency (with new home page mobile) what do you think about using the number too?
![icecreampartiesmobile](https://cloud.githubusercontent.com/assets/20116181/21689006/8ad74928-d334-11e6-96b5-eb54e15f7fb6.jpg)

**Comment by vcfolger** [comment]
How would this appear on desktop? This is not a mobile-only change. I'd prefer just the button, no phone number, towards the top of the page but under the header...that makes sense scanning down the page so you know what you're booking (read: Ice Cream Special Events, then Book Now / rather than Book Now, then Ice Cream Parties.

**Comment by kelly-wolfe** [comment]
Oh, I thought that since the BOOK MY EVENT is at the top to the right on desktop, this would be a non-issue. There is also a link at the end of the first paragraph. I guess ideally it would look like this, but I don't know how hard it will be to make this change.  I imagine they aren't planning on paying for it :)
![icecreampartiesmobile](https://cloud.githubusercontent.com/assets/20116181/21902687/7a844f6a-d8c2-11e6-9c42-f25f499d15c6.jpg)
![screen shot 2017-01-12 at 12 24 00 pm](https://cloud.githubusercontent.com/assets/20116181/21902688/7a86d8a2-d8c2-11e6-819c-66d6383d2e40.png)
Josh, how big a deal is this? Suggestions?

**Comment by vcfolger** [comment]
Kelly, I think this is a change I could make (after you switch the banner image out), it's just linking the banner image to the Book Now page. 

Do you think the button should be centered for consistency with the animation, the only other place where we have a linkable banner?

FYI this is a non-issue in my mind too, but Bobby and Michelle feel strongly that there needs to be a big honking CTA on this page, in addition to the side call-out. They've been pushing for this change for awhile and I tried to add that link in the first paragraph but they didn't think it was enough.

**Comment by kelly-wolfe** [comment]
![banner2](https://cloud.githubusercontent.com/assets/20116181/21910653/8fe7feae-d8e2-11e6-9705-373aa3b9ab7c.jpg)

**Comment by vcfolger** [comment]
Okay I don't mean to beat this into the ground but I really don't want to hear Michelle's diatribe again about having a big button....is this going to be big enough for her? I don't know. I know consistency is important but I wonder if we should go bigger on the button. Especially since it'll be much smaller for mobile.

**Comment by kelly-wolfe** [comment]
![banner3](https://cloud.githubusercontent.com/assets/20116181/21935474/464a92de-d973-11e6-9fc3-ef81e62ab090.jpg)

**Comment by vcfolger** [comment]
This should fit the bill. Could swap the image on the site?

**Comment by joshbolinger** [comment]
swap the image?
