### ISSUE TITLE
Need to update stock photo - Parties page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#109]
http://66.147.244.191/~outhesi4/ice-cream-parties/

The image of the ice cream sundae still has a watermark

**Comment by kelly-wolfe** [comment]
Lose some space below logo so it's centered.
![screen shot 2017-01-12 at 11 50 59 am](https://cloud.githubusercontent.com/assets/20116181/21901534/be84fa70-d8bd-11e6-80b4-a8e15312069f.png)
