### ISSUE TITLE
Too much space above/below logo in header?

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#110]
Example: http://66.147.244.191/~outhesi4/ice-cream-distributor/

**Comment by kelly-wolfe** [comment]
Lose space below logo, so centered vertically. 
![screen shot 2017-01-12 at 11 50 59 am](https://cloud.githubusercontent.com/assets/20116181/21901571/e582d41c-d8bd-11e6-8f48-06ba74871b48.png)

**Comment by joshbolinger** [comment]
I moved it up about 10px to match the animation on the home page. Or did you want to tighten up the area around the logo for the whole site?

**Comment by vcfolger** [comment]
Whole site please
