### ISSUE TITLE
"SCS Credit Card Processing"?

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#114]
Why does this say "SCS credit card processing? This probably just needs to come out?
![screen shot 2017-01-12 at 10 36 49 am](https://cloud.githubusercontent.com/assets/20050245/21898653/20ade546-d8b3-11e6-8c90-3ec024e56eea.png)

**Comment by joshbolinger** [comment]
oh that was required by TransFirst guys. What would you prefer it to be?

**Comment by vcfolger** [comment]
Okay, how about just "Credit Card Payment"
