### ISSUE TITLE
Tax exempt functionality

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#117]
If the user selects that they are a tax exempt entity in the checkout process, the order should not charge tax. Currently it does charge tax if that is the selection.

**Comment by vcfolger** [comment]
Josh, have you gotten to take a look at this yet?

**Comment by joshbolinger** [comment]
checking

**Comment by vcfolger** [comment]
Josh, where do we stand on this?

**Comment by vcfolger** [comment]
Now there are two places to enter the state tax ID so I'm checking with the client to see if we can remove the static Tax ID field.
