### ISSUE TITLE
About us image caption

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#12]
http://hitmebaby.com/about-us/

Move this copy into the caption:
The City of Stafford honored Southern Ice Cream’s service to the community, by dedicating July 3rd to then owners Sharon and Michael Johnston, and they served as parade marshals on July 4th , 2009.

**Comment by netintelpro** [comment]
No problem.

Any thoughts on the font size, alignment ,etc regarding caption type?
![caption](https://cloud.githubusercontent.com/assets/2364031/17088154/2ff4d17a-51dd-11e6-8d64-0d035b72f5d8.png)

**Comment by vcfolger** [comment]
Addressing this in a separate ticket.
