### ISSUE TITLE
Customer Order Confirmation Email

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#120]
I went back to when you originally sent me these emails and copied my response below, taking out the items that are already done. Only additional question here: what is “TXP Card Processing” for Payment Method?
CUSTOMER EMAIL:
- Could you replace the text at the beginning of the email ("Your order has now been...") with the two paragraphs under "Email Body" below?

(From Copy Deck)

Email Body

Thank you for booking your event with Southern Ice Cream. We will contact you by phone within the next 72 hours to discuss your event and finalize any remaining details. If you need assistance at any time, do not hesitate to call us at 281-499-9837 or email info@southernicecream.com. 

_Important: Cancellations must be received at least 48 hours prior to your event. Failure to do so will result in being charged 20% of your total order._

**Comment by joshbolinger** [comment]
done
