### ISSUE TITLE
Images matching callouts - About us

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#14]
http://hitmebaby.com/about-us/

The images in the distribution callout and the schools call-out are not correct. I believe the truck that's with the Schools call-out can go down to the Distribution callout, and the Schools call-out has a photo of a few different ice cream pops.

**Comment by netintelpro** [comment]
Is this what you had in mind?
http://hitmebaby.com/about-us/

**Comment by vcfolger** [comment]
Kelly, could you confirm this one and "Close" if complete?

**Comment by kelly-wolfe** [comment]
NO. In the callouts folder, they are named to go with each call out. The one for Ice Cream Party is 
![winicecreamparty](https://cloud.githubusercontent.com/assets/20116181/17483070/2f54612c-5d4a-11e6-8ad7-7cfcf9e71d1e.png)

It sounds like C, that you don't like this photo though. We discussed in another issue and it has yet to be resolved. The photo that is there now called bookmyevent.png, so...it should go on the book my event call out.

**Comment by joshbolinger** [comment]
the callouts are all over the place, I cant tell whats been changed and what still needs to be changed. I am going to close all these tickets and we can go through each page one by one if needed
