### ISSUE TITLE
Add global footer

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#15]
Per copy deck, footer should be:

![image](https://cloud.githubusercontent.com/assets/20050245/16440813/f39bbe16-3d8a-11e6-8b9f-0eda9b554631.png)

**Comment by netintelpro** [comment]
Is there a comp showing what footer is to look like? This would be helpful. Thanks.

**Comment by vcfolger** [comment]
Kelly, could you comp this up?

**Comment by joshbolinger** [comment]
done
