### ISSUE TITLE
About Us image

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#16]
http://hitmebaby.com/about-us/

The image that's currently on the About us page is fine and something like this should stay on this page, but with the caption it would be better to have a photo of the Parade Marshalls or specific charitable activity. Does SIC have an image for this?

**Comment by kelly-wolfe** [comment]
Not that i have seen. I will look again.

**Comment by kelly-wolfe** [comment]
I did not find a photo that would work. I have re-designed the page and I think it makes more sense this way.  The banner image is one of the new ones Bobby took and then a stock photo to go with the caption at the bottom. 
![aid](https://cloud.githubusercontent.com/assets/20116181/16525438/fffcf646-3f71-11e6-8aab-85aa70aa896a.png)
![aboutus](https://cloud.githubusercontent.com/assets/20116181/16525437/fffc7446-3f71-11e6-9adc-0761e2a2232d.png)

**Comment by kelly-wolfe** [comment]
Here's screen capture of what it should look like:
![screen shot 2016-07-01 at 9 48 22 am](https://cloud.githubusercontent.com/assets/20116181/16525461/1bca3910-3f72-11e6-9bff-c84fa96d28a7.png)

**Comment by vcfolger** [comment]
This works for me. Bobby and Michelle might see the stock photo and finally send us an actual photo...they must have something from the parade. I sent them a note. Keeping this assigned to myself until I hear back from them.

**Comment by netintelpro** [comment]
Is this better?
http://hitmebaby.com/about-us/

Any comments,suggestions or observations?

**Comment by vcfolger** [comment]
caption text displaying larger than body; with this fixed it should work!
![screen shot 2016-08-05 at 12 39 33 pm](https://cloud.githubusercontent.com/assets/20050245/17445311/eba0fa7c-5b09-11e6-837d-94e74791b3d7.png)

**Comment by joshbolinger** [comment]
this didnt really work side by side, so I broke them in different lines

http://scs.joshbolinger.com/about-us/
