### ISSUE TITLE
Call out corrections

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#17]
http://hitmebaby.com/ice-cream-push-cart-party-rentals/

For the Book My Event Call-out, "Plan my ice cream party!" should be the button copy, with no body copy.

For the Win an Ice Cream Party call-out, all that copy would fall into the turquoise button, based on the design of the call-outs.  Can you try this and see how it looks? (CTA/button text would be: “Like” us on Facebook for your chance to win an ice cream social!)

**Comment by netintelpro** [comment]
Is this what you had in mind?
![plan my event screenshot](https://cloud.githubusercontent.com/assets/2364031/17087402/8a32b026-51ce-11e6-98dc-5610a617fe3b.png)

**Comment by vcfolger** [comment]
Let's use the "Win an ice cream party" callout from this page:
http://hitmebaby.com/schools/

Make all "Win an ice cream party" call-outs match. Just be sure the text is not being forced to a weird break, as it currently is on the schools page (also mentioned in a separate issue)
