### ISSUE TITLE
Contact right-hand call-out: Global Change

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#18]
Please change the button text in this callout to "Submit a Request"

**Comment by netintelpro** [comment]
Just to be clear...are you saying change button text here in every page?
![ice cream truck party rentals scs](https://cloud.githubusercontent.com/assets/2364031/17076844/e00613fa-5082-11e6-91de-202b193d98f3.png)

**Comment by vcfolger** [comment]
yes

**Comment by vcfolger** [comment]
yes

**Comment by joshbolinger** [comment]
done

http://scs.joshbolinger.com/ice-cream-parties/ice-cream-truck-party-rentals/
