### ISSUE TITLE
Add images to "Ice Cream Truck Parties" page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#19]
I think you have the images that go on this page, but let me know if not. (currently there is placeholder copy indicating where the images should go)

http://hitmebaby.com/ice-cream-parties/ice-cream-truck-party-rentals/

**Comment by netintelpro** [comment]
![truck3](https://cloud.githubusercontent.com/assets/2364031/17076817/dfd5ffcc-5081-11e6-98e3-e5f7d4a76c9d.png)
![truck2](https://cloud.githubusercontent.com/assets/2364031/17076813/dfd32d4c-5081-11e6-8229-93cbb533d88b.png)
![leftbanner](https://cloud.githubusercontent.com/assets/2364031/17076816/dfd5f7ca-5081-11e6-8af9-719592140358.png)
![bars](https://cloud.githubusercontent.com/assets/2364031/17076815/dfd3b1f4-5081-11e6-9c9f-9a52d3d01f60.png)
![truck1](https://cloud.githubusercontent.com/assets/2364031/17076814/dfd34980-5081-11e6-8631-cec23f836746.png)

**Comment by netintelpro** [comment]
These are images I have under ice cream truck party rentals folder in 'images for John' given by Kelly.
However I'm not sure which images go where on this page.

**Comment by vcfolger** [comment]
Kelly, can you help?

**Comment by kelly-wolfe** [comment]
So I literally have to layout every page? I practically did. I thought I was going above and beyond.
I would just read the copy and drop images where it seems appropriate based on the many examples. I thought I included enough examples where that would be easy.  Is it common for the designer to have to layout every page?
