### ISSUE TITLE
Homepage slider arrow buttons on mobile

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#21]
John, the left/right arrows on the homepage banners for the mobile site are impossible to tap. Is there a solution for this? Make them bigger for mobile or something?

**Comment by netintelpro** [comment]
Yes they can be made bigger.
But isnt the slider a place holder for animation? 

If slider is temporary place holder for animation  do we still need to put the time in for bigger buttons

**Comment by vcfolger** [comment]
yes, still need to address this. we are doing a slider where the first of three banners is animated
