### ISSUE TITLE
Replace Blue Bunny Trailer Image Callout

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#22]
Use one of the photos sent by Bobby for the Blue Bunny call-out on this page:
http://hitmebaby.com/ice-cream-distributor/mobile-vending/

Kelly, could you attach the image to this "Issue" and assign to John?

**Comment by kelly-wolfe** [comment]
![bluebunnytrailer](https://cloud.githubusercontent.com/assets/20116181/17059801/8abbc732-4fec-11e6-9121-1eb4efee6bf4.png)

**Comment by netintelpro** [comment]
complete
