### ISSUE TITLE
Mobile Vending Side Call-out

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#23]
On the mobile vending right side call-outs:
http://hitmebaby.com/ice-cream-distributor/mobile-vending/tips/
http://hitmebaby.com/ice-cream-distributor/

These should not have a button, but the red heading text should be linked. The call-out on the "Mobile Vending Tips" page needs the image added.

**Comment by netintelpro** [comment]
Done
