### ISSUE TITLE
Distribution Area Side Call-out Image

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#26]
Kelly, here is an example of  Distribution Area callout:
http://hitmebaby.com/ice-cream-distributor/food-service/

The text being so tiny is a little bothersome. Could you zoom into/crop out one part of the map (maybe centering on Houston) or use a different image of a truck or something, OR use the maps as-is except without text (city names, I think)?

**Comment by kelly-wolfe** [comment]
Yes, I think w/o text works fine.
![distributionarea](https://cloud.githubusercontent.com/assets/20116181/16851558/b507d8f6-49c9-11e6-869c-c1246a9a388a.png)

**Comment by kelly-wolfe** [comment]
Hi John, can you swap out attached image for the distribution call outs? Here's one 
http://hitmebaby.com/ice-cream-distributor/food-service/
![distributionarea](https://cloud.githubusercontent.com/assets/20116181/16851636/09a7e2ac-49ca-11e6-8840-4c6beba431dc.png)

**Comment by netintelpro** [comment]
Hows this
http://hitmebaby.com/ice-cream-distributor/food-service/
