### ISSUE TITLE
Add anchor links

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#27]
http://hitmebaby.com/ice-cream-distributor/food-service/

Under "Proud Distributor of..." header, the list should all be anchor linked to each of the subheads below.

**Comment by netintelpro** [comment]
Can't find Pacific Valley Dairy website (maybe they need one?). No link posted.

http://hitmebaby.com/ice-cream-distributor/food-service/

**Comment by vcfolger** [comment]
You misunderstood -- should anchor link to content below, not link out

**Comment by joshbolinger** [comment]
done

http://scs.joshbolinger.com/ice-cream-distributor/food-service/
