### ISSUE TITLE
Images Needed: Blue Bunny Scoops

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#28]
On this page: http://hitmebaby.com/ice-cream-distributor/food-service/

There is a note to include a grid of scoops, similar to the way it is on the current site here:
http://southernicecreamtx.com/food-service

Please upload image files to this issue and assign to John.

**Comment by kelly-wolfe** [comment]
I don't see those in the Blue Bunny folder. Should I just use the ones on the current site?

**Comment by vcfolger** [comment]
Yes, if we don't have any new scoops.

**Comment by vcfolger** [comment]
Kelly, we still need these.

**Comment by kelly-wolfe** [comment]
I found some better images on another site. Was going to ask you if you think it is worth the time to use them, or to just use the shitty ones on their existing site. I think new consistent will look much better but the way things are going, it may just makes sense to go the easy route. 

Blue bunny uses the package...
https://www.bluebunny.com/flavors/all

but the scoop is pretty easy to find too:
https://www.google.com/search?q=blue+bunny+scoop+ice+cream&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwignIK6_rHOAhXHeCYKHZiJA44QsAQILA&biw=1174&bih=879

**Comment by joshbolinger** [comment]
I assume this is resolved now?

http://scs.joshbolinger.com/ice-cream-distributor/food-service/
