### ISSUE TITLE
Open PDF in a new window from "Download full brochure" link

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#29]
http://hitmebaby.com/schools/
[School Book 2015_Condensed.pdf](https://github.com/vcfolger/southernicecreamtx.com/files/362986/School.Book.2015_Condensed.pdf)
PDF attached.

**Comment by vcfolger** [comment]
See above; link is "Download full brochure"

**Comment by joshbolinger** [comment]
http://scs.joshbolinger.com/schools/
