### ISSUE TITLE
Remove teal buttons from right-side call-outs on Schools page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#31]
http://hitmebaby.com/schools/

**Comment by netintelpro** [comment]
Is this what you had in mind?
http://hitmebaby.com/schools/

**Comment by vcfolger** [comment]
Yes, just please fix this break ... seems to be forcing a line break in a strange spot for this one:
“Like” us on Facebook for your chance to win an ice cream social!

**Comment by joshbolinger** [comment]
is this better?

http://scs.joshbolinger.com/schools/
