### ISSUE TITLE
Side call out images

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#32]
Are the images for these right side call-outs correct?
http://hitmebaby.com/ice-cream-push-cart-party-rentals/

The bars seem kind of unrelated to Book My Event to me.  It would tie in better to me to show the SIC ice cream truck or more of an event image. 

For "Win an Ice Cream Party," the little girl seems to be enjoying her ice cream and it's a nice image, but it doesn't really say "free ice cream social" to me. Maybe I expect more than one person since the text calls it an ice cream social. Am I being to picky?

**Comment by kelly-wolfe** [comment]
That image is for schools. This one is for Book My Event...
![bookmyevent](https://cloud.githubusercontent.com/assets/20116181/16850782/46a189be-49c6-11e6-9aae-82297978295f.png)

"Win an Ice Cream Party"
You didn't like my other image of people eating at the party b/c of their cups, so I simplified, but I see what you are saying. I just spent another 30 min looking and all images have cones or cups similar to the one you didn't like.  See attached.
![screen shot 2016-07-14 at 1 29 51 pm](https://cloud.githubusercontent.com/assets/20116181/16850986/1e539a46-49c7-11e6-8867-690cd86b9610.png)

**Comment by vcfolger** [comment]
Does John have the correct images in the folder or should we open a new issue with replacement images attached?

**Comment by kelly-wolfe** [comment]
He has always had the correct images in the correct folders. I honestly don't understand why he can't figure it out.

**Comment by joshbolinger** [comment]
I went through and touched up the sidebar callouts as I could, but I cant tell whats supposed to go where. 

There are some that still look off like here
http://scs.joshbolinger.com/ice-cream-push-cart-party-rentals/

http://cl.bolinger.co/hVPR
