### ISSUE TITLE
Distribution Map Image

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#33]
http://hitmebaby.com/ice-cream-distributor/service-area/

You are going to be annoyed at me, but I think the maps are a bit  too small. I think they would make more sense broken up into one TX map, shown after the TX subhead, and one LA map, shown after the LA subhead. The maps could be placed in-line with the text.

**Comment by kelly-wolfe** [comment]
Well, does it matter that ,like so many other photos, is supposed to go across the whole top of page instead of squeezing next to the call out?  This is happening all over the site btwy.

**Comment by vcfolger** [comment]
I stand by my original comment -- state maps broken up under each state makes more sense and will allow for bigger maps...maybe each map can go in a banner spanning the horizontal space if you don't like in-line images?

**Comment by kelly-wolfe** [comment]
That's fine. I'll try and get to it today if I can.

**Comment by joshbolinger** [comment]
I made some changes here if you want to check

http://scs.joshbolinger.com/ice-cream-distributor/service-area/
