### ISSUE TITLE
Trade out red map pin for a bomb pop on Contact page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#35]
http://hitmebaby.com/contact-us/

Kelly, do you need to give John an image for this? If so, attach here and assign the issue to John. If not, assign to John.

**Comment by kelly-wolfe** [comment]
Actually, that was just a placeholder I got off of that florida site. I should use something else. Either a different ice cream or a star.  So sorry, I meant to address that...I think star.

**Comment by kelly-wolfe** [comment]
Maybe it being illustrated is enough to set it apart?  IDK...
![mappop](https://cloud.githubusercontent.com/assets/20116181/16850395/7d2fa7b0-49c4-11e6-97bb-08126dac49c3.png)

**Comment by netintelpro** [comment]
This is not an image but an embedded google map. But there is a way to change pin.
http://hitmebaby.com/contact-us/

**Comment by kelly-wolfe** [comment]
It's tiny, but I kinda like it like that.
