### ISSUE TITLE
Front-end double-check

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#36]
Khadijah,
Could you take a quick pass at the test site against the comps and make any tweaks/fixes you see? There are some little visual things that still need to be addressed that we haven't really addressed in individual issues, because it looked like that just needed another pass by dev before we started entering specific issues. What comes to mind is that there is a bar at the top of the site that appears then disappears again when scrolling. 

Comps are attached for reference.
[16-SIC-006 web-design-otherpages2 (1).pdf](https://github.com/vcfolger/southernicecreamtx.com/files/372082/16-SIC-006.web-design-otherpages2.1.pdf)

**Comment by vcfolger** [comment]
Has this been addressed?

**Comment by joshbolinger** [comment]
this should all be done
