### ISSUE TITLE
Schools page image update

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#38]
Hi Josh, see new images and mock up attached. All you are really doing is updating the image. Please don't hesitate to tell me if I can do something to make your life easier on any of this stuff.  :)
[16-SIC-006 web-design-schools page.pdf](https://github.com/vcfolger/southernicecreamtx.com/files/459701/16-SIC-006.web-design-schools.page.pdf)
![nutrition](https://cloud.githubusercontent.com/assets/20116181/18320441/76b2a54e-74ef-11e6-8129-37d1da7f0639.png)

**Comment by kelly-wolfe** [comment]
OH sorry, and take out those cone place holder images too! I incorporated them all into one image. Its rather large and weird, but what was desired!

**Comment by kelly-wolfe** [comment]
Just noticed, I also added a subhead. "Nutritional Information"  should be added as well. Maybe I'll get them all in one go on the next "issue"!

**Comment by joshbolinger** [comment]
I think this is right, could you confirm?

http://scs.joshbolinger.com/schools/
