### ISSUE TITLE
Food Service page image update

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#39]
http://scs.joshbolinger.com/ice-cream-distributor/food-service/

1.) Please use banner1.png as top banner image.

2.) Please delete "Pacific Valley Dairy" and text all text associated with them.

3.) Add images for each of the remaining distributors. The image should go just above associated subhead.  They are labeled to match subhead and are numbered. The preview shows them in reverse order. 

4.) Please make all red subheads the same size as they are on Ice Cream Parties page.

FYI- I didn't comp out the whole thing so feel free to call all me with questions. 5127856623

![5-bluebunny2banners](https://cloud.githubusercontent.com/assets/20116181/18323947/a09d883c-74ff-11e6-82f7-13159c187e42.png)
![4-bluebunny1banners](https://cloud.githubusercontent.com/assets/20116181/18323949/a09f8cea-74ff-11e6-9c72-3b8a64ec9b51.png)
![3-rosatiicebanners](https://cloud.githubusercontent.com/assets/20116181/18323950/a0dcccfe-74ff-11e6-9402-95081fc684dd.png)
![2-houseofflavorsbanner](https://cloud.githubusercontent.com/assets/20116181/18323963/ad79f0f4-74ff-11e6-9b13-a0c05bb4eb8f.png)
![1-ashbybanner](https://cloud.githubusercontent.com/assets/20116181/18323981/c007f2ac-74ff-11e6-9003-00cf9fe8b7c8.png)
![banner1](https://cloud.githubusercontent.com/assets/20116181/18323948/a09e226a-74ff-11e6-91ff-36c9aa263b66.png)

**Comment by joshbolinger** [comment]
done

http://scs.joshbolinger.com/ice-cream-distributor/food-service/
