### ISSUE TITLE
Homepage Sliders

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#4]
We created left/right arrows for the homepage sliders; match these and add the turquoise buttons.
![screen shot 2016-06-28 at 3 07 41 pm](https://cloud.githubusercontent.com/assets/20050245/16430663/536ab4d0-3d42-11e6-9369-9049c3c66d18.png)

**Comment by kelly-wolfe** [comment]
To be honest, I prefer it the way John has it w/o the turquoise buttons.

**Comment by vcfolger** [comment]
We can leave the scroll arrows how they are on the test site, but they are impossible to tap on mobile. I'll open a new issue for this. 

John, you do still need to add the turquoise CTA buttons.

**Comment by netintelpro** [comment]
Do slider buttons matter if we will be using animation?

**Comment by vcfolger** [comment]
Yes, as I mentioned in the other issue, there are still going to be 3 banner "sliders". The first of these three is supposed to be animated.
