### ISSUE TITLE
Ice Cream Push Cart Party Rentals image update

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#40]
http://scs.joshbolinger.com/ice-cream-push-cart-party-rentals/

1.) Please ad this photo for short banner:
![banner1](https://cloud.githubusercontent.com/assets/20116181/18400555/1037c5fc-769c-11e6-9490-181c461bebb8.png)

2.) Ad this one left aligned with text wrap in line with "How it works" subhead text
![pushcart2](https://cloud.githubusercontent.com/assets/20116181/18400333/ffbc8ce0-769a-11e6-8ec9-9322f40963bc.png)

3.) Ad these 3 example packages horizonally below "Sample Pricing" subhead text. 
![package1](https://cloud.githubusercontent.com/assets/20116181/18400627/5b2dd664-769c-11e6-9522-e84cf5d93c23.png)

![package2](https://cloud.githubusercontent.com/assets/20116181/18400358/20687df0-769b-11e6-8f85-21e609c0a55f.png)
![package3](https://cloud.githubusercontent.com/assets/20116181/18400360/206d178e-769b-11e6-9a32-34ce7a0d9aac.png)

See attached pdf for reference to image placement only (ignore call-outs and fonts etc).
[16-SIC-006 web-design-pushcartpartyrentals.pdf](https://github.com/vcfolger/southernicecreamtx.com/files/464683/16-SIC-006.web-design-pushcartpartyrentals.pdf)

4.) Please change call-out copy size and font to match example below:
![screen shot 2016-09-09 at 2 40 57 pm](https://cloud.githubusercontent.com/assets/20116181/18400428/7959a68c-769b-11e6-8cf7-451fa071c999.png)

**Comment by kelly-wolfe** [comment]
Feel free to adjust the size of the #2 image. Its looking a bit big ;/

**Comment by joshbolinger** [comment]
this is all in here, but im not sure what you are asking for the sidebar call out

http://scs.joshbolinger.com/ice-cream-push-cart-party-rentals/

**Comment by kelly-wolfe** [comment]
In Firefox your side bar call out headline fonts and sizes are not correct. Should match #4 above with Collector Comic and all caps etc. This is what it looks like on my screen.
![screen shot 2016-09-19 at 9 00 44 am](https://cloud.githubusercontent.com/assets/20116181/18634700/d1fdc8dc-7e47-11e6-8cd4-cc6ef2879701.png)

**Comment by kelly-wolfe** [comment]
whoops!  I thought I changed all this; not sure why it didn't work.  Sorry!   This page should look like this: (headline copy is wrong on screen capture, please ignore.)

![screen shot 2016-09-13 at 2 01 43 pm](https://cloud.githubusercontent.com/assets/20116181/18635180/b8464ac0-7e49-11e6-97de-4060528591d5.png)

Please replace image of guy with pushcart to 
![pushcart2](https://cloud.githubusercontent.com/assets/20116181/18635093/6063a596-7e49-11e6-9355-9e5249b55c05.png)

Note the "sample pricing" section formatting and images.
![crowdpleaser](https://cloud.githubusercontent.com/assets/20116181/18635324/3d0253f8-7e4a-11e6-955d-3327911dcfe3.png)
![goodhumor](https://cloud.githubusercontent.com/assets/20116181/18635323/3cfd52fe-7e4a-11e6-847b-9159f7aa9491.png)
![kidsparty](https://cloud.githubusercontent.com/assets/20116181/18635325/3d12406a-7e4a-11e6-818d-6ee56d0c9fc3.png)
![southernfavs](https://cloud.githubusercontent.com/assets/20116181/18635326/3d17a410-7e4a-11e6-8b08-66d44b1bdb02.png)

banner image should be short instead of going all the way across.

**Comment by kelly-wolfe** [comment]
See above.

**Comment by joshbolinger** [comment]
that top image didnt quite fit how you had it, so I made it work another way

http://scs.joshbolinger.com/ice-cream-push-cart-party-rentals

**Comment by vcfolger** [comment]
This doesn't look like Kelly's comp on my screen -- inset image too small, sample pricing section not in a grid with images maybe too large

**Comment by joshbolinger** [comment]
the comp is not to proper scale. Its much more narrow than the actual site (which is still smaller than normal) so most comps dont match the spacing of the site correctly

**Comment by vcfolger** [comment]
It's funny because Kelly says the site is much narrower than her comps...you're saying the site is wider than her comps?

**Comment by joshbolinger** [comment]
see on how the comps only need 3 paragraphs lined up next to the photo 

http://cl.bolinger.co/hsm7

but on the actual site, it takes 4, plus 1 hidden paragraph 

http://cl.bolinger.co/hsPL

**Comment by kelly-wolfe** [comment]
Is it the bottom items that are causing a problem?  Why would this banner be different than any of the other short banners ex: bagged and dry ice.

**Comment by kelly-wolfe** [comment]
All of the call-outs should use Comic Collector font all caps and be centered.
