### ISSUE TITLE
Mobile Vending page updates

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#41]
1.)  Please delete existing image.
2.) Add this image as short banner: 
![banner1](https://cloud.githubusercontent.com/assets/20116181/18441542/0d79456e-78d3-11e6-94a9-da01e0ce476d.png)

**Comment by joshbolinger** [comment]
done

http://scs.joshbolinger.com/ice-cream-distributor/mobile-vending/

**Comment by vcfolger** [comment]
Kelly, as discussed the bottom right photo needs to be a different image/not the distribution truck
