### ISSUE TITLE
Ice Cream Truck Party Rentals image update

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#42]
http://scs.joshbolinger.com/ice-cream-parties/ice-cream-truck-party-rentals/

1.) JOSH Please Add this image as large banner across the top.
![truckpartyrentals-banner](https://cloud.githubusercontent.com/assets/20116181/18450835/40cd6252-78fa-11e6-90e1-1c802f58d997.png)
2.) Fix call-out subheads size and font
3.) Add 2 truck images and ice cream into copy. See screen shot below for placement.
![truck1](https://cloud.githubusercontent.com/assets/20116181/18452381/3c641afc-7900-11e6-80c3-94fc344a6ec6.png)
![truck2](https://cloud.githubusercontent.com/assets/20116181/18452382/3c70a470-7900-11e6-936e-c583276c8f66.png)
![samples](https://cloud.githubusercontent.com/assets/20116181/18452473/93b6f6b2-7900-11e6-834f-8fdbca2bcb4d.png)

CHRISTINA- I find this page to be confusing. How many different trucks do they have? Seems like there should be a subheader for each option no?

**Comment by kelly-wolfe** [comment]
Forgot to attach screen capture.
![screen shot 2016-09-12 at 3 01 55 pm](https://cloud.githubusercontent.com/assets/20116181/18452545/e6c5362a-7900-11e6-9d23-9c30e91ef2cb.png)

**Comment by joshbolinger** [comment]
this is all in there, but the copy doesnt match, what is correct?

http://scs.joshbolinger.com/ice-cream-parties/ice-cream-truck-party-rentals/

**Comment by kelly-wolfe** [comment]
The screen capture is wrong. Its good on site.
