### ISSUE TITLE
Party Packages

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#43]
Here are the 4 existing packages. I missed one and mis-labeled before.
![southernfavspack](https://cloud.githubusercontent.com/assets/20116181/18481506/03123e8a-79a2-11e6-9443-c7ccb57d5492.png)
![goodhumorpack](https://cloud.githubusercontent.com/assets/20116181/18481505/0311afa6-79a2-11e6-875f-0ed1a2ed935f.png)
![kidspartypackage](https://cloud.githubusercontent.com/assets/20116181/18481507/031351ee-79a2-11e6-95e1-976dc19ac05a.png)
![crowd pleaser](https://cloud.githubusercontent.com/assets/20116181/18481504/03115aa6-79a2-11e6-80ae-04958bde0985.png)

**Comment by joshbolinger** [comment]
where does this go?

**Comment by kelly-wolfe** [comment]
Right sorry, these go on book my event page. We are still working on it, so ignore for now.
