### ISSUE TITLE
ice Cream Sundae Party image update

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#44]
http://scs.joshbolinger.com/ice-cream-parties/sundae-parties/
1.) Use this image as short banner:
![sundae](https://cloud.githubusercontent.com/assets/20116181/18487722/ec91d4b2-79bb-11e6-9b61-bb22294113ac.png)
2.) Use this image to the left of the bulletted list and above "Sample Pricing"
![sundae2](https://cloud.githubusercontent.com/assets/20116181/18487802/3dd6f6ae-79bc-11e6-9163-e73c8a2ac082.png)

**Comment by joshbolinger** [comment]
this is done
http://scs.joshbolinger.com/ice-cream-parties/sundae-parties/
