### ISSUE TITLE
Book My Event page

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#45]
Hi Josh,
please make changes to this page to reflect recent developments. http://scs.joshbolinger.com/ice-cream-parties/book-my-event/

Here is screen capture of mock up.
![screen shot 2016-10-03 at 3 01 51 pm](https://cloud.githubusercontent.com/assets/20116181/19051946/88985c6e-897a-11e6-842c-8796a83bf277.png)

Here is banner image:
![bookmyeventbanner](https://cloud.githubusercontent.com/assets/20116181/19052029/ddcc5ffa-897a-11e6-9173-91f095573347.png)

Here are images for shopping cart.
![vintagetruck400](https://cloud.githubusercontent.com/assets/20116181/19051967/a1786a76-897a-11e6-807c-f7d399d41259.png)
![vintagetruck300](https://cloud.githubusercontent.com/assets/20116181/19051969/a17ac014-897a-11e6-898f-a9656f4d9bf7.png)
![vintagetruck200](https://cloud.githubusercontent.com/assets/20116181/19051972/a18601a4-897a-11e6-8903-d8ec5090656c.png)
![vintagetruck150](https://cloud.githubusercontent.com/assets/20116181/19051968/a1798410-897a-11e6-9ad4-3d6fcb35dee7.png)
![vintagetruck100](https://cloud.githubusercontent.com/assets/20116181/19051970/a17b0894-897a-11e6-87d8-9202ee438163.png)
![truckparty400](https://cloud.githubusercontent.com/assets/20116181/19051971/a18100fa-897a-11e6-8bde-22861a07048a.png)
![truckparty300](https://cloud.githubusercontent.com/assets/20116181/19051975/a188f418-897a-11e6-9c8f-957a2a6bca4b.png)
![truckparty200](https://cloud.githubusercontent.com/assets/20116181/19051973/a1866f5e-897a-11e6-8b40-8ad66712609f.png)
![truckparty150](https://cloud.githubusercontent.com/assets/20116181/19051974/a187adce-897a-11e6-9538-886beed36c30.png)
![truckparty100](https://cloud.githubusercontent.com/assets/20116181/19051976/a189e81e-897a-11e6-8e5b-d6e79cc0d2ea.png)
![sundaeparty400](https://cloud.githubusercontent.com/assets/20116181/19051977/a18db6d8-897a-11e6-95fa-d782dac4a58c.png)
![sundaeparty300](https://cloud.githubusercontent.com/assets/20116181/19051979/a197616a-897a-11e6-8dcf-8b519649c942.png)
![sundaeparty200](https://cloud.githubusercontent.com/assets/20116181/19051978/a19455ba-897a-11e6-8b06-1ef501269a87.png)
![sundaeparty150](https://cloud.githubusercontent.com/assets/20116181/19051981/a19a5096-897a-11e6-8b5a-36c778264fa1.png)
![sundaeparty100](https://cloud.githubusercontent.com/assets/20116181/19051983/a1a3e1f6-897a-11e6-809f-0607455259a1.png)
![southernfavs192](https://cloud.githubusercontent.com/assets/20116181/19051980/a197d88e-897a-11e6-9f33-cb13959b0047.png)
![kidspartypackage168](https://cloud.githubusercontent.com/assets/20116181/19051982/a19e327e-897a-11e6-9ab9-008490918a8e.png)
![goodhumor96](https://cloud.githubusercontent.com/assets/20116181/19051985/a1a80060-897a-11e6-9d57-17fd4ed10222.png)
![crowdpleaser264](https://cloud.githubusercontent.com/assets/20116181/19051984/a1a5bdfa-897a-11e6-86bc-32f94ad90ee6.png)

All other info such as copy I think you have. Check glip or call us with questions. Thanks so much!

**Comment by vcfolger** [comment]
Kelly, I have all the events added into the back-end. I went to add the images, but when I try to grab them off github there is a long automatically generated filename for each, and I know you mentioned naming them with descriptive names...

Maybe ZIP a folder with the thumbnail images and upload that to github instead?

**Comment by kelly-wolfe** [comment]
I added them to dropbox.  Folder called Shopping cart images. Let me know that you received them ok.

---

KELLY WOLFE  |  Art Director+  |  512.785.6623  |  wolfe-design.com http://wolfe-design.com/
