### ISSUE TITLE
Distribution Logos

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#46]
http://scs.joshbolinger.com/ice-cream-distributor/

Kelly, I can't find the issue where you uploaded/fixed logos for this page.

**Comment by kelly-wolfe** [comment]
HI Josh,
Please take off Pacific Valley dairy and wonderbread  logo and add hersheys and wonder ice cream and Wells Blue Bunny logos below.  Also please center the call-out copy.

![wonder](https://cloud.githubusercontent.com/assets/20116181/19567028/f50244f2-96b1-11e6-96ab-da6d551f85bf.png)
![bluebunny](https://cloud.githubusercontent.com/assets/20116181/19567029/f502627a-96b1-11e6-8f89-65e8a920f14e.png)
![hersheys](https://cloud.githubusercontent.com/assets/20116181/19567030/f502d75a-96b1-11e6-8726-7e06b0467a8a.png)

**Comment by kelly-wolfe** [comment]
whoops and this one...
![houseofflavors](https://cloud.githubusercontent.com/assets/20116181/19571022/04ecb3ec-96c2-11e6-8e98-ba5231ccaa71.png)

**Comment by joshbolinger** [comment]
http://scs.joshbolinger.com/ice-cream-distributor/
