### ISSUE TITLE
mobile vending page

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#47]
http://scs.joshbolinger.com/ice-cream-distributor/mobile-vending/
This page is meant to be formatted like the dry ice page. The image should be tucked in next to the call-outs like so.
http://scs.joshbolinger.com/dry-ice-and-bagged-ice/

Trade out the banner image for this one please.
![banner1](https://cloud.githubusercontent.com/assets/20116181/19571675/8d4aabb6-96c4-11e6-956b-bb5e5984c227.png)

**Comment by vcfolger** [comment]
Josh, this banner still has the incorrect image.

**Comment by joshbolinger** [comment]
looks right to me

**Comment by vcfolger** [comment]
Look at the bottom right truck. It's still the incorrect image.

**Comment by kelly-wolfe** [comment]
Hey y'all, I just replaced the image myself. It is the exact same size as the previous but is showing up pixelated. Any ideas as to why?

**Comment by joshbolinger** [comment]
looks find to me now, I assume you fixed it
