### ISSUE TITLE
Animation on Homepage

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#49]
Kelly, three things on this animation:
1 - The animation should loop, but it stops on the background red at the end.
2 - The buttons should be clickable, they currently are not
3 - The animation is way down the page and there's a bunch of white space that shouldn't be there. 

Let me know if you can address these or if you need Josh to take a look.

**Comment by kelly-wolfe** [comment]
1. I can probably figure out the loop.  
2. I figured out how to do it yesterday, but I'm not 100% sure on what url to use b/c in the dev site, everything is "joshbolinger.com"  I assume it should be www.southernicecream.com/about-us but..that will currently link to their crappy current site no?  
3. I know, I don't understand why that is happening and I told Josh about it yesterday.

**Comment by vcfolger** [comment]
Use the test site URLs for links; they will be updated when we go live.
