### ISSUE TITLE
Ice Cream Parties Side Call-out / About Us

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#50]
http://scs.joshbolinger.com/about-us/

The header for the Ice Cream Parties call-out needs to be centered.

Does the height of these call-outs change depending on the length of the content, or does less content simply mean more white space?

**Comment by vcfolger** [comment]
also on this page, same thing.
![screen shot 2016-10-26 at 11 49 15 pm](https://cloud.githubusercontent.com/assets/20050245/19754918/446e3882-9bd7-11e6-81a5-635f0fd7864e.png)

**Comment by vcfolger** [comment]
Ah sorry! Didn't paste in second link 
http://scs.joshbolinger.com/ice-cream-parties/

**Comment by vcfolger** [comment]
Closing because I just realized this call-out is not correct at all. It is not in the copy deck anywhere.

**Comment by kelly-wolfe** [comment]
CHeck out my issue I created yesterday. We discussed the headlines in callouts.
