### ISSUE TITLE
Ice Cream Parties/Book My Event Call-out

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#51]
Not sure why there is a call-out that is completely off from the copy deck, but all the "Ice Cream Parties" call-outs should actually be this:

Book My Event
Plan my ice cream party! (links to http://scs.joshbolinger.com/book-my-event/)

Example of correct call-out is on this page, except note the alignment of the header's call-out needs to be centered: http://scs.joshbolinger.com/dry-ice-and-bagged-ice/

"Ice Cream Party" call-outs that need to be replaced with Book My Event call-outs are on:
http://scs.joshbolinger.com/about-us/
http://scs.joshbolinger.com/ice-cream-parties/
http://scs.joshbolinger.com/ice-cream-push-cart-party-rentals/

Book My Event is here but needs to be replaced with the correct version, this one is wrong:
http://scs.joshbolinger.com/ice-cream-parties/sundae-parties/

**Comment by kelly-wolfe** [comment]
See titles.  Maybe I should have named the first one “winicecreamparty”  idk. There is definitely something going on with the call outs. Its like they can’t read the names or something.

---

KELLY WOLFE  |  Art Director+  |  512.785.6623  |  wolfe-design.com http://wolfe-design.com/
