### ISSUE TITLE
Incorrect Side Call-outs/About us

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#52]
http://scs.joshbolinger.com/about-us/

Side call-outs should be the following, with the header of each call-out as the link:
![image](https://cloud.githubusercontent.com/assets/20050245/19755318/90e92fac-9bda-11e6-8c8d-10c152f4287b.png)

**Comment by vcfolger** [comment]
There should not be blue buttons. There is no text for buttons. The header should be the link.

**Comment by joshbolinger** [comment]
huh?

**Comment by vcfolger** [comment]
Ok this has gone too far down the wrong path to correct it now, the way it is will work so I'm not going to ask to change it. Closing.
