### ISSUE TITLE
FEMA image size/caption

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#58]
http://scs.joshbolinger.com/about-us/

Any suggestions to make this image/caption look better in the layout?

**Comment by kelly-wolfe** [comment]
I put a new image in. Its the same problem I had with the new mobile vending banner. It is the exact same size and file type, but for some reason, its showing up blurry, like it's super small.

**Comment by kelly-wolfe** [comment]
I figured it out!
