### ISSUE TITLE
Product Order Change on Book My Event

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#61]
http://scs.joshbolinger.com/wp-admin/edit.php?post_type=product

I can't figure out how to assign an order to the products -- per the client, please:

Move the Southern Favs Package above the Original Good Humor Truck and the Sunday Party package

**Comment by kelly-wolfe** [comment]
I think this is something that should wait until we know everything about the changes to this page.  I think of Josh's raking leaves analogy.

**Comment by vcfolger** [comment]
This can be changed now. I should be able to take care of most client changes to Book My Event, but I can't figure out this one, so I need Josh's help. New analogy: low-hanging fruit :-)

**Comment by kelly-wolfe** [comment]
Seems to me like one of those things that is more complicated than it seems and that's why you can't find it.  But...if it is low hanging fruit, great!

**Comment by vcfolger** [comment]
I figured this one out.
