### ISSUE TITLE
Image Editing on Ice Cream Push Carts Page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#62]
http://scs.joshbolinger.com/ice-cream-push-cart-party-rentals/

If I try to edit the image that's in the content area, it does a strange thing and changes back to the previous image. I would like the image to be bigger...

**Comment by joshbolinger** [comment]
which image do you want to change?

**Comment by kelly-wolfe** [comment]
I think she was talking about the image that was there previously. I changed it entirely, so unless she wants to change it back...this is closed.
