### ISSUE TITLE
Need sub-bullets - Ice Cream Sundaes Page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#67]
http://scs.joshbolinger.com/ice-cream-parties/sundae-parties/

I can't figure out how to make sub bullets appear correctly (indented further and possibly with a different bullet type). When editing page, I see open circles for some items on the list that should be sub-bullets, but they are not indented and they do not show as a different bullet type on the live page.

**Comment by joshbolinger** [comment]
the theme isnt setup for this, so I made a quick fix, let me know if this works
