### ISSUE TITLE
Distributor Page/Logos

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#69]
Update the logos on this page: http://scs.joshbolinger.com/ice-cream-distributor/

Changes needed are:
Remove Totally Bananas. 
Replace the blue bunny logo with the one Bobby sent 
Replace the Hershey’s logo with the one Bobby sent 

(Kelly could you attach the two new logos here and assign to Josh?)

**Comment by vcfolger** [comment]
Kelly did you send Josh the logos separately?

**Comment by kelly-wolfe** [comment]
Nope, I attached....Here they are again...
![bluebunny](https://cloud.githubusercontent.com/assets/20116181/19944413/d67a8794-a109-11e6-8c4c-62d997f28f07.png)
![hersheys](https://cloud.githubusercontent.com/assets/20116181/19944415/d6885446-a109-11e6-82ee-9f4fea81972a.png)
