### ISSUE TITLE
Homepage Callout Spacing (3-across)

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#7]
![screen shot 2016-06-28 at 2 53 10 pm](https://cloud.githubusercontent.com/assets/20050245/16430217/2093b950-3d40-11e6-98be-5505f4ea2538.png)

Callouts on homepage need to be fixed -- running off the edge of the page in "actual size" zoom on Chrome/Mac. Also can you move up the buttons a bit more so there's not so much dead space between buttons and copy.

**Comment by netintelpro** [comment]
Callouts on homepage need to be fixed -- running off the edge of the page in "actual size" zoom on Chrome/Mac.  - Fixed

**Comment by netintelpro** [comment]
Buttons remain and layout for page width 991px or less need to be addressed
