### ISSUE TITLE
Call-out styles are inconsistent

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#71]
This is super frustrating, I don't thing it's anyone's fault, but a result of call-outs being written a certain way, designed a different way, and coded both ways or a combination of both ways. Ugh...

The call-outs in this section http://scs.joshbolinger.com/ice-cream-distributor/ and this page: http://scs.joshbolinger.com/dry-ice-and-bagged-ice/ are, for the most part, consistent with the way they were written. However, on the rest of the site they were adapted to work with the blue CTA button that was in the design (but which never had copy associated with it). At this point, I think we're committed to the blue button style.

Update the Contact Us callout onttp://scs.joshbolinger.com/ice-cream-distributor/ to be the same as elsewhere (like here: http://scs.joshbolinger.com/dry-ice-and-bagged-ice/)

On the Dry Ice page, the Win an Ice Cream Party and Book My Event call-outs should match the ones here: http://scs.joshbolinger.com/ice-cream-parties/

To be consistent with other pages, **change black text into blue button with text/link on the button rather than the call-outs' red headers**. This applies to Mobile Vending, Schools, Mobile Vending Tips, Distribution Area, and Wholesale Distribution call-outs, all on this page and its sub-pages:
http://scs.joshbolinger.com/ice-cream-distributor/

**Comment by joshbolinger** [comment]
I know, they are not only styled differently on each page, but they are all programmed different plus they dont match the design and often dont match the deck so I never know which is correct. I had assumed that the ones with the buttons were correct so thats what I have been using

**Comment by vcfolger** [comment]
Most of these are fixed now, but here is where the text needs to be changed to the blue button style/linked: 

To be consistent with other pages, change black text into blue button with text/link on the button rather than the call-outs' red headers. This applies to Mobile Vending, Schools, Mobile Vending Tips, Distribution Area, and Wholesale Distribution call-outs, all on this page and its sub-pages:
http://scs.joshbolinger.com/ice-cream-distributor/

**Comment by joshbolinger** [comment]
I dont know if this makes sense. Lets discuss

**Comment by vcfolger** [comment]
Josh, we never fixed this but it was closed for some reason. The meat of it is:

To be consistent with other pages, change black text into blue button with text/link on the button rather than the call-outs' red headers. This applies to Mobile Vending, Schools, Mobile Vending Tips, Distribution Area, and Wholesale Distribution call-outs, all on this page and its sub-pages:
http://scs.joshbolinger.com/ice-cream-distributor/

**Comment by joshbolinger** [comment]
"change black text into blue button with text/link on the button rather than the call-outs' red headers"

Typos or am I not understanding?

**Comment by vcfolger** [comment]
Rephrased:
 there is a red header in each of the side call outs. The  read header should not be  a link. 

 Each call out should have a blue button which is linked. Instead of adding more text and a button to the callouts that don't have a button, I want to make the black "body copy" under the header into the blue button.  This means that some of the buttons will be  kind of long, but oh well.

 A good example of a place we did this is the "win an ice cream party by liking us on Facebook" side callout.
