### ISSUE TITLE
Contact Us / Move text

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#76]
Can we move this copy above the map:
![image](https://cloud.githubusercontent.com/assets/20050245/19916101/048cdd60-a085-11e6-88ee-30518701fb7f.png)

Also, could we format the submit button to match better to other buttons on the site?
![screen shot 2016-11-01 at 10 48 02 pm](https://cloud.githubusercontent.com/assets/20050245/19916139/5d9bc772-a085-11e6-8dc5-33e8516fecd1.png)

**Comment by kelly-wolfe** [comment]
C, I don't want that copy to be above the map. I treated the map like the banners on the other pages, so I actually moved it below.

**Comment by vcfolger** [comment]
To me, the map is one of the least important elements on the page because most people are not coming to the SIC facility, they probably need to call or email. Do you think having the map there visually like a banner is more important than getting the user the information they need faster? It seemed strange to me that the map would have the priority spot on this page.

**Comment by kelly-wolfe** [comment]
I don't think it is significantly faster to have it above the map and it significantly impacts the way it looks.

**Comment by vcfolger** [comment]
Josh, what's left on this issue is the question:
Also, could we format the submit button to match better to other buttons on the site?

If it's a pain I can live without this change.
