### ISSUE TITLE
Animation buttons HUGE on mobile.

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/southernicecreamtx.com#78]
Josh, any clue how to make the buttons in the animation shrink down proportionately on mobile?  They are staying the same size while all else is shrinking.

**Comment by joshbolinger** [comment]
it looks like under Visability and Behavior, there are some settings for mobile and responsive. I didnt want to jack up your animation if you want to play with those settings yourself

http://cl.bolinger.co/iAqq

**Comment by vcfolger** [comment]
Kelly, assigning this to you...
