### ISSUE TITLE
New Event Thumbnail Needed: Ooh La La

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#80]
Please make a thumbnail for a new Push Cart package and upload to the test site: 
Name: Ooh La La

Ice cream included: 
Magnum Double Peanut Butter Bar
Oreo King Cone
Snicker's Candy Bar
Birthday Party Bar
Good Humor Chocolate Cookie Sandwich

**Comment by kelly-wolfe** [comment]
I am assuming the snickers candy bar is actually an ice cream bar. I found a pic of that, but I'm going to need more info on the "Birthday Party Bar." When I do a search for that it's mostly birthday party pics at bars.  :)

**Comment by kelly-wolfe** [comment]
it's up.
