### ISSUE TITLE
Header/menu fonts

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#81]
Josh, Maybe you're working on the site now,  but in case you aren't aware, the header and menu fonts are currently not working/going to a serif font.

**Comment by joshbolinger** [comment]
when did this start happening? Have you made any changes?

**Comment by vcfolger** [comment]
I noticed it this morning. I made changes this morning, but the fonts were already looking wrong when I made changes.

Last I looked (before this morning), I think it was correct...
