### ISSUE TITLE
Dry Ice Picture

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#84]
Michelle wants to change out the banner on the ice page to a photo of actual dry ice. I guess she is worried people will see the dry ice drinks and think SIC sells something like that. See her note below:
![screen shot 2016-12-02 at 12 33 23 pm](https://cloud.githubusercontent.com/assets/20050245/20845635/a771b348-b88b-11e6-800f-8ee74b5f053e.png)

**Comment by kelly-wolfe** [comment]
this one work?
![stock-photo-dry-ice-102846803](https://cloud.githubusercontent.com/assets/20116181/20847823/3953e8ea-b895-11e6-8d7b-34871c5ff79c.jpg)

**Comment by vcfolger** [comment]
Yeah I think so. Kind of ugly surface it's sitting on but not too bad.

**Comment by kelly-wolfe** [comment]
There are very limited options
