### ISSUE TITLE
Book My Event Side Call-outs - Image change

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#85]
![image](https://cloud.githubusercontent.com/assets/20050245/20845700/f0be3ecc-b88b-11e6-928f-04bca551cd27.png)

It's the little stickers on the ice creams that's bothering Michelle, I think. She she wants to take them off (as a second option, if it's not possible to remove the stickers, she suggests using a group of Blue Bunny products instead)

**Comment by kelly-wolfe** [comment]
Book my event was always supposed to be this image...
![bookmyevent](https://cloud.githubusercontent.com/assets/20116181/20847981/d8bf00fe-b895-11e6-9448-1e74b29a2ade.png)

**Comment by vcfolger** [comment]
Ok weird. Is this a Josh change then?

**Comment by vcfolger** [comment]
Josh, please change all the "Book My Event" side call-outs to use the image above, with the girls wearing sunglasses. I'm not sure when this got switched around. Here are the pages with that call-out:

http://66.147.244.191/~outhesi4/ice-cream-parties/
http://66.147.244.191/~outhesi4/ice-cream-push-cart-party-rentals/
http://66.147.244.191/~outhesi4/ice-cream-parties/ice-cream-truck-party-rentals/
http://66.147.244.191/~outhesi4/ice-cream-parties/sundae-parties/
http://66.147.244.191/~outhesi4/dry-ice-and-bagged-ice/
