### ISSUE TITLE
Need New Ice Cream Sundae Party Thumbnail

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#88]
Michelle did not provide detail on this one, but the image you're using now is not exactly a sundae (no toppings). Can I help search for stock photos and maybe we send Michelle a few options before dropping one into the thumb?

**Comment by kelly-wolfe** [comment]
whoops, I meant to assign you a dfferent one :)

**Comment by kelly-wolfe** [comment]
I don't know what thumbnail you are talking about here.

**Comment by vcfolger** [comment]
Sorry, the one on Book My Event.
http://66.147.244.191/~outhesi4/book-my-event/

**Comment by kelly-wolfe** [comment]
OHHHH now I know what you mean. I told M she needed to find one, or if you want to look, go ahead.

**Comment by vcfolger** [comment]
What sites are you getting stock photos from?

**Comment by kelly-wolfe** [comment]
istock and adobe stock



_______________________________________________________
KELLY WOLFE  |  Art Director+  |  512.785.6623  |  wolfe-design.com <http://wolfe-design.com/>
