### ISSUE TITLE
Ice Cream Parties Event Category Photos

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#89]
http://66.147.244.191/~outhesi4/ice-cream-parties/

They are requesting you add a border around the event category photos on this page. This seems like a pretty random/objective change request, but since you already use color coded borders for the event thumbnails, maybe it's a good opportunity to pull through that color coding to this parent page.

**Comment by kelly-wolfe** [comment]
yeah thats fine.

**Comment by kelly-wolfe** [comment]
Does this mean I should buy the stock image? I might as well do it all at once.
