### ISSUE TITLE
Homepage body copy spacing

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#9]
Body copy currently extends across the entire content area. Should have a margin that makes it extend only as wide as the three call-outs below, per comp.

**Comment by netintelpro** [comment]
This is addressed. Let me know how it looks.
http://hitmebaby.com/

**Comment by kelly-wolfe** [comment]
Looks backwards on Firefox, the top should span the whole space and the callouts at the bottom should have the margin. 
![screen shot 2016-08-01 at 8 59 22 am](https://cloud.githubusercontent.com/assets/20116181/17296377/9d2bccd2-57c6-11e6-8b66-2637a5d3147d.png)
