### ISSUE TITLE
Contact Us Map/Business Description

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#92]
http://66.147.244.191/~outhesi4/contact-us/

![image](https://cloud.githubusercontent.com/assets/20050245/20846389/0849c464-b88f-11e6-801f-26b2722dd8a7.png)
![screen shot 2016-12-02 at 12 57 33 pm](https://cloud.githubusercontent.com/assets/20050245/20846400/0ff1dd78-b88f-11e6-97cc-7f0cfcf219c3.png)

**Comment by joshbolinger** [comment]
this is somones personal map. Does it belong to her google account?

**Comment by vcfolger** [comment]
Kelly, did you create this map/maybe you are the one who needs to make these changes?

**Comment by kelly-wolfe** [comment]
John made the map.

**Comment by kelly-wolfe** [comment]
I am not sure what needs to be done here.

**Comment by joshbolinger** [comment]
really the best bet here is for the client to go here (https://www.google.com/maps/d/u/0/) and make their own map so they can set it up and edit it whenever and however they want
