### ISSUE TITLE
Fix "E"s on animation

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#94]
Per client:

![image](https://cloud.githubusercontent.com/assets/20050245/20846482/72ef2a66-b88f-11e6-93c1-3698de87fbd7.png)

**Comment by kelly-wolfe** [comment]
So I figured it out. Weirdly, Collector Comic appears to be all cap font, but it has a difference, the e's change whether lower or upper case. NEVER seen this before!  Sooo...I guess I need to know for sure which she prefers. I assume she likes the less loopy version, which is the capitol.

**Comment by kelly-wolfe** [comment]
I'll just test michelle.

**Comment by kelly-wolfe** [comment]
She likes the uppercase less loopy e, Josh can you make sure the font is set to all caps throughout the site?  I'll change it in the other places. ARG!

**Comment by kelly-wolfe** [comment]
Ok, I fixed it in the animation.  Josh, just need you to make sure "Collector Comic" font is always set to all caps throughout site to avoid loopy "e's
