### ISSUE TITLE
Additional Social Media Icons

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#95]
Should we make this change or ask them to pay for the addition? What do you think Kelly?

![image](https://cloud.githubusercontent.com/assets/20050245/20846503/931eb310-b88f-11e6-871a-6e0ccf0bf920.png)

**Comment by kelly-wolfe** [comment]
I added the images to library. Josh, they are already larger than they appear, can you up the size a little and add the new icons etc?

**Comment by vcfolger** [comment]
Josh, I don't see this update.

**Comment by joshbolinger** [comment]
sorry, I miss read that. Its there now
