### ISSUE TITLE
Book My Event Side Call-out image not working on mobile

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#97]

**Comment by joshbolinger** [comment]
could you clarify this more. Do you mean here? http://cl.bolinger.co/idMk

**Comment by vcfolger** [comment]
Hm this looks ok to me now. But I did notice the wrong image on the About page. It should match the screenshot you posted to this issue

**Comment by joshbolinger** [comment]
what screenshot?

**Comment by vcfolger** [comment]
The screenshot you posted above, it's: http://cl.bolinger.co/idMk

**Comment by joshbolinger** [comment]
so the image should not be http://cl.bolinger.co/il6E, it should instead be http://cl.bolinger.co/idMk ? Did you guys change that? If so, why? Was the image being used somewhere else and you tried changing it for that place?
