### ISSUE TITLE
Ice Cream Sundae Photo Replacement - Book My Event Thumbnail

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/southernicecreamtx.com#99]
Use this for the ice cream sundae "Book My Event"
![stock-photo-three-scoops-of-ice-creams-with-cone-on-white-background-70877956](https://cloud.githubusercontent.com/assets/20050245/21147910/2caf8dda-c11c-11e6-9c3c-188ac3161fb4.jpg)

http://66.147.244.191/~outhesi4/book-my-event/

**Comment by kelly-wolfe** [comment]
I added the image to library.

**Comment by joshbolinger** [comment]
done
